(function(){
    'use strict';
    var ms=null,cb=null,cfid=null;
    function sp(i){document.querySelectorAll('.page').forEach(function(p){p.classList.remove('active')});var e=document.getElementById(i);if(e)e.classList.add('active');}
    function st(ic,m,d){d=d||2000;var t=document.createElement('div');t.className='toast';t.innerHTML='<div class=\"toast-icon\">'+ic+'</div><div>'+m+'</div>';document.body.appendChild(t);setTimeout(function(){t.remove()},d);}
    function hd(){document.getElementById('dialog-overlay').classList.add('hidden');}
    function fd(t){var d=new Date(t);return d.getFullYear()+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+String(d.getDate()).padStart(2,'0');}
    function ft(t){var d=new Date(t);return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
    function sd(o){var v=document.getElementById('dialog-overlay'),b=document.getElementById('dialog-body');var h='';if(o.icon)h+='<div class=\"dialog-icon\">'+o.icon+'</div>';if(o.title)h+='<div class=\"dialog-title\">'+o.title+'</div>';if(o.text)h+='<div class=\"dialog-text\">'+o.text+'</div>';if(o.input)h+='<div style=\"margin-bottom:16px\"><input type=\"text\" id=\"di\" class=\"input-dialog-input\" value=\"'+o.input+'\" maxlength=\"10\"></div>';if(o.progress)h+='<div class=\"dialog-progress\"><div class=\"dialog-progress-bar\" id=\"dpb\"></div></div>';b.innerHTML=h;var a=document.createElement('div');a.className='dialog-anges';(o.buttons||[{label:'\u786e\u5b9a'}]).forEach(function(b2){var bn=document.createElement('button');bn.className='dialog-btn'+(b2.danger?' danger':'');bn.textContent=b2.label;bn.onclick=function(){hd();if(b2.action)b2.action();};a.appendChild(bn);});b.appendChild(a);v.classList.remove('hidden');if(o.input)setTimeout(function(){var i=document.getElementById('di');if(i)i.focus();},200);return {updateProgress:function(p){var bar=document.getElementById('dpb');if(bar)bar.style.width=p+'%';},updateText:function(t){var e=b.querySelector('.dialog-text');if(e)e.textContent=t;},getInput:function(){var ip=document.getElementById('di');return ip?ip.value:'';}};}
    function sc(){if(ms){ms.getTracks().forEach(function(t){t.stop()});ms=null;}['camera-preview','folder-camera-preview'].forEach(function(i){var v=document.getElementById(i);if(v)v.srcObject=null;});}
    function gh(){sc();cfid=null;sp('page-home');loadFolders();}
    document.getElementById('btn-new-back').onclick=gh;
    document.getElementById('btn-confirm-back').onclick=function(){cb=null;sp('page-new');};
    document.getElementById('btn-manual-back').onclick=function(){sp('page-new');};
    document.getElementById('btn-folder-back').onclick=gh;
    document.getElementById('btn-folder-camera-back').onclick=function(){sc();sp('page-folder');};
    document.getElementById('btn-new-folder').onclick=function(){sp('page-new');setTimeout(startCam,300);};
    document.getElementById('btn-manual-input').onclick=function(){sc();sp('page-manual');document.getElementById('input-plate-manual').focus();};
    document.getElementById('btn-upload-plate').onclick=function(){sc();document.getElementById('plate-upload-input').click();};
    document.getElementById('btn-manual-save').onclick=async function(){var p=document.getElementById('input-plate-manual').value.trim();if(!p){st('\u26a0','\u8bf7\u8f93\u5165\u8f66\u724c\u53f7\u7801');return;}await dcf(p,null);};
    document.getElementById('input-plate-manual').onkeydown=function(e){if(e.key==='Enter')document.getElementById('btn-manual-save').click();};
    document.getElementById('plate-upload-input').onchange=async function(e){var f=e.target.files[0];if(!f)return;var bl=f;sc();sp('page-confirm');document.getElementById('confirm-image').src=URL.createObjectURL(bl);var h=document.getElementById('confirm-hint');h.textContent='\u6b63\u5728\u8bc6\u522b\u8f66\u724c\u2026';document.getElementById('btn-confirm-save').disabled=true;var r=await recognizePlate(bl,function(p){h.textContent='\u8bc6\u522b\u4e2d\u2026'+Math.round(p*100)+'%';});cb=bl;var ip=document.getElementById('input-plate');if(r&&r.plate){ip.value=r.plate;h.textContent='\u8bc6\u522b\u5b8c\u6210\u8bf7\u786e\u8ba4';h.style.color='var(--success)';}else{if(r.quotaExceeded){ip.value='';ip.placeholder='\u767e\u5ea6API\u989d\u5ea6\u5df2\u7528\u5b8c\uff0c\u8bf7\u624b\u52a8\u8f93\u5165';h.textContent='\u767e\u5ea6API\u989d\u5ea6\u5df2\u7528\u5b8c\uff0c\u8bf7\u624b\u52a8\u8f93\u5165';h.style.color='var(--danger)';}else if(r.error){ip.value='';ip.placeholder=r.error;h.textContent=r.error;h.style.color='var(--danger)';}else{ip.value='';ip.placeholder='\u8bc6\u522b\u5931\u8d25\u8bf7\u624b\u52a8\u8f93\u5165';h.textContent='\u8bc6\u522b\u5931\u8d25\u8bf7\u624b\u52a8\u8f93\u5165';h.style.color='var(--danger)';}}document.getElementById('btn-confirm-save').disabled=false;e.target.value='';};
    document.getElementById('btn-capture').onclick=function(){var v=document.getElementById('camera-preview');if(!v||!v.videoWidth){st('\u26a0','\u76f8\u673a\u672a\u5c31\u7eea');return;}var c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(async function(bl){cb=bl;sc();sp('page-confirm');document.getElementById('confirm-image').src=URL.createObjectURL(bl);var h=document.getElementById('confirm-hint');h.textContent='\u6b63\u5728\u8bc6\u522b\u8f66\u724c\u2026';document.getElementById('btn-confirm-save').disabled=true;var r=await recognizePlate(bl,function(p){h.textContent='\u8bc6\u522b\u4e2d\u2026'+Math.round(p*100)+'%';});var ip=document.getElementById('input-plate');if(r&&r.plate){ip.value=r.plate;h.textContent='\u8bc6\u522b\u5b8c\u6210\u8bf7\u786e\u8ba4';h.style.color='var(--success)';}else{if(r.quotaExceeded){ip.value='';ip.placeholder='\u767e\u5ea6API\u989d\u5ea6\u5df2\u7528\u5b8c\uff0c\u8bf7\u624b\u52a8\u8f93\u5165';h.textContent='\u767e\u5ea6API\u989d\u5ea6\u5df2\u7528\u5b8c\uff0c\u8bf7\u624b\u52a8\u8f93\u5165';h.style.color='var(--danger)';}else if(r.error){ip.value='';ip.placeholder=r.error;h.textContent=r.error;h.style.color='var(--danger)';}else{ip.value='';ip.placeholder='\u8bc6\u522b\u5931\u8d25\u8bf7\u624b\u52a8\u8f93\u5165';h.textContent='\u8bc6\u522b\u5931\u8d25\u8bf7\u624b\u52a8\u8f93\u5165';h.style.color='var(--danger)';}}document.getElementById('btn-confirm-save').disabled=false;},'image/jpeg',0.95);};
    document.getElementById('btn-retake').onclick=function(){cb=null;document.getElementById('confirm-image').src='';document.getElementById('input-plate').value='';sp('page-new');setTimeout(function(){startCam(document.getElementById('camera-preview'))},300);};
    document.getElementById('btn-confirm-save').onclick=async function(){var p=document.getElementById('input-plate').value.trim();if(!p){st('\u26a0','\u8bf7\u8f93\u5165\u8f66\u724c\u53f7\u7801');return;}await dcf(p,cb);};
    async function startCam(v){if(!v)v=document.getElementById('camera-preview');try{if(ms)ms.getTracks().forEach(function(t){t.stop()});ms=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=ms;await v.play();}catch(e){console.error(e);st('\u26a0','\u65e0\u6cd5\u6253\u5f00\u76f8\u673a');}}
    async function dcf(p,b){try{var fid=await createFolder(p,b);st('\u2705','\u5df2\u521b\u5efa: '+p);cb=null;document.getElementById('confirm-image').src='';document.getElementById('input-plate').value='';document.getElementById('input-plate-manual').value='';cfid=fid;sp('page-folder');await loadFolderDetail(fid);}catch(e){console.error('\u521b\u5efa\u5931\u8d25:',e);st('\u274c','\u521b\u5efa\u5931\u8d25:'+e.message);}}
    async function loadFolders(){var c=document.getElementById('folder-list');var e=document.getElementById('empty-state');if(!e){c.innerHTML='<div class=\"empty-state\" id=\"empty-state\"><div class=\"empty-icon\">\ud83d\udcf7</div><h2 class=\"empty-title\">\u8fd8\u6ca1\u6709\u88c5\u8f66\u8bb0\u5f55</h2><p class=\"empty-desc\">\u70b9\u51fb\u4e0b\u65b9\u6309\u94ae\u5f00\u59cb\u65b0\u5efa</p></div>';e=document.getElementById('empty-state');}try{var folders=await getTodayFolders();if(!folders||!folders.length){c.innerHTML='';c.appendChild(e);e.style.display='flex';return;}e.style.display='none';var html='';folders.forEach(function(f,i){var s=folders.length-i;html+='<div class=\"folder-card\" data-id=\"'+f.id+'\"><div class=\"folder-icon\">\ud83d\ude9b</div><div class=\"folder-info\"><div class=\"folder-name\">'+s+'.'+f.plateNumber+'</div><div class=\"folder-meta\">'+(f.photoCount||0)+'\u5f20\u00b7'+ft(f.createdAt)+'</div></div><div class=\"folder-card-actions\"><button class=\"folder-card-btn\" data-action=\"edit\" data-id=\"'+f.id+'\" title=\"\u4fee\u6539\">\u270f</button><button class=\"folder-card-btn danger\" data-action=\"delete\" data-id=\"'+f.id+'\" title=\"\u5220\u9664\">\ud83d\uddd1</button></div><div class=\"folder-arrow\"><svg viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><polyline points=\"9 18 15 12 9 6\"/></svg></div></div>';});c.innerHTML=html;c.appendChild(e);e.style.display='none';c.querySelectorAll('.folder-card').forEach(function(el){el.addEventListener('click',function(ev){if(ev.target.closest('.folder-card-btn'))return;cfid=parseInt(this.dataset.id);sp('page-folder');loadFolderDetail(cfid);});});c.querySelectorAll('[data-action=\"edit\"]').forEach(function(b){b.onclick=function(ev){ev.stopPropagation();ef(parseInt(b.dataset.id));};});c.querySelectorAll('[data-action=\"delete\"]').forEach(function(b){b.onclick=function(ev){ev.stopPropagation();dfc(parseInt(b.dataset.id));};});}catch(ex){console.error('\u5237\u65b0\u5931\u8d25:',ex);c.innerHTML='<div style=\"text-align:center;padding:40px;color:var(--danger)\">\u5237\u65b0\u5931\u8d25: '+ex.message+'</div>';c.appendChild(e);e.style.display='none';}}
    function ef(fid){getFolder(fid).then(function(f){if(!f){st('\u274c','\u4e0d\u5b58\u5728');return}var d=sd({icon:'\u270f',title:'\u4fee\u6539\u8f66\u724c',text:'\u4fee\u6539\u4e3a\uff1a',input:f.plateNumber,buttons:[{label:'\u53d6\u6d88'},{label:'\u4fdd\u5b58',action:async function(){var np=d.getInput().trim();if(!np){st('\u26a0','\u8bf7\u8f93\u5165');return}try{await updateFolder(fid,{plateNumber:np});st('\u2705','\u5df2\u66f4\u65b0');loadFolders()}catch(e){st('\u274c','\u66f4\u65b0\u5931\u8d25')}}}]});}).catch(function(e){st('\u274c','\u83b7\u53d6\u5931\u8d25')});}
    function dfc(fid){getFolder(fid).then(function(f){if(!f){st('\u274c','\u4e0d\u5b58\u5728');return}sd({icon:'\ud83d\uddd1',title:'\u5220\u9664\u6587\u4ef6\u5939',text:'\u786e\u5b9a\u5220\u9664 "'+f.plateNumber+'" \u5417\uff1f\u5c06\u5220\u9664\u6587\u4ef6\u5939\u5185\u6240\u6709\u7167\u7247\u3002',buttons:[{label:'\u53d6\u6d88'},{label:'\u5220\u9664',danger:true,action:async function(){try{await deleteFolder(fid);st('\ud83d\uddd1','\u5df2\u5220\u9664');if(cfid===fid){cfid=null;sp('page-home')}loadFolders()}catch(e){st('\u274c','\u5220\u9664\u5931\u8d25')}}}]});}).catch(function(e){st('\u274c','\u83b7\u53d6\u5931\u8d25')});}
    async function loadFolderDetail(fid){try{var f=await getFolder(fid);if(!f){st('\u274c','\u6587\u4ef6\u5939\u4e0d\u5b58\u5728');sp('page-home');return;}var fs=await getTodayFolders();var s=fs.findIndex(function(x){return x.id===fid});document.getElementById('folder-title').textContent=(fs.length-s)+'.'+f.plateNumber;rp(await getFolderPhotos(fid));}catch(e){console.error(e);}}
    function rp(ps){var c=document.getElementById('folder-photos');if(!ps||!ps.length){c.innerHTML='<div class=\"empty-state\"><div class=\"empty-icon\">\ud83d\udcf7</div><h2 class=\"empty-title\">\u8fd8\u6ca1\u6709\u7167\u7247</h2><p class=\"empty-desc\">\u70b9\u51fb\u4e0b\u65b9\u6309\u94ae\u62cd\u7167\u6216\u4e0a\u4f20</p></div>';return;}var h='<div class=\"photo-grid\">';ps.forEach(function(p){var u=URL.createObjectURL(p.data);h+='<div class=\"photo-card\"><img src=\"'+u+'\" alt=\"\" loading=\"lazy\"><button class=\"photo-delete\" data-pid=\"'+p.id+'\">\u00d7</button><div class=\"photo-overlay\">'+(p.isPlatePhoto?'\u8f66\u724c\u7167\u7247':ft(p.createdAt))+'</div></div>';});h+='</div>';c.innerHTML=h;c.querySelectorAll('.photo-delete').forEach(function(b){b.onclick=function(ev){ev.stopPropagation();var pid=parseInt(b.dataset.pid);sd({icon:'\ud83d\uddd1',title:'\u5220\u9664\u7167\u7247',text:'\u786e\u5b9a\u5220\u9664\uff1f',buttons:[{label:'\u53d6\u6d88'},{label:'\u5220\u9664',danger:true,action:async function(){await deletePhoto(pid,cfid);loadFolderDetail(cfid)}}]});};});}
    document.getElementById('btn-take-photo').onclick=function(){if(!cfid)return;sp('page-camera');setTimeout(function(){startCam(document.getElementById('folder-camera-preview'))},300);};
    document.getElementById('btn-folder-capture').onclick=function(){var v=document.getElementById('folder-camera-preview');if(!v||!v.videoWidth){st('\u26a0','\u76f8\u673a\u672a\u5c31\u7eea');return;}var c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(async function(bl){sc();try{await savePhoto(cfid,bl,false);sp('page-folder');await loadFolderDetail(cfid);st('\u2705','\u5df2\u4fdd\u5b58');}catch(e){console.error(e);st('\u274c','\u4fdd\u5b58\u5931\u8d25');sp('page-folder');}},'image/jpeg',0.85);};
    document.getElementById('btn-upload-photo').onclick=function(){if(!cfid)return;var ip=document.getElementById('file-input');ip.value='';ip.onchange=async function(ev){var fs=ev.target.files;if(!fs||!fs.length)return;var n=0;for(var i=0;i<fs.length;i++){if(await spf(fs[i],cfid))n++;}if(n)st('\u2705','\u5df2\u4fdd\u5b58'+n+'\u5f20');ip.onchange=null;};ip.click();};
    async function spf(file,fid){try{await savePhoto(fid,await ci(file,1920,0.85),false);await loadFolderDetail(fid);return true;}catch(e){return false;}}
    function ci(blob,mx,q){return new Promise(function(rs){var img=new Image(),url=URL.createObjectURL(blob);img.onload=function(){URL.revokeObjectURL(url);var w=img.width,h=img.height;if(w>mx||h>mx){var r=mx/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r);}var c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);c.toBlob(rs,'image/jpeg',q);};img.onerror=function(){rs(blob)};img.src=url;});}
    document.getElementById('btn-clear-all').onclick=function(){sd({icon:'🗑',title:'清空所有文件夹',text:'确定要删除今天的所有文件夹吗？此操作不可撤销。',buttons:[{label:'取消'},{label:'确定清空',danger:true,action:async function(){try{await clearAllFolders();st('✅','已清空所有文件夹');loadFolders()}catch(e){console.error(e);st('❌','清空失败')}}}]});};document.getElementById('btn-export').onclick=async function(){try{var all=await getAllFolders();if(!all||!all.length){st('\ud83d\udcc2','\u6682\u65e0\u6570\u636e');return;}var dlg=sd({icon:'\ud83d\udce6',title:'\u6b63\u5728\u5bfc\u51fa',text:'\u6b63\u5728\u6253\u5305\u2026',progress:true,buttons:[]});var zip=new JSZip(),root=zip.folder('\u6c7d\u8fd0');var total=0,tf=await getTodayFolders();for(var i=0;i<tf.length;i++){var f=tf[i],s=tf.length-i,n=s+'.'+f.plateNumber,fz=root.folder(n);var ps=await getFolderPhotos(f.id);for(var j=0;j<ps.length;j++){var ab=await blobToArrayBuffer(ps[j].data);fz.file(ps[j].filename,ab);total++;}dlg.updateProgress(Math.round((i+1)/tf.length*90));dlg.updateText('\u6253\u5305: '+n);}dlg.updateProgress(95);dlg.updateText('\u538b\u7f29\u4e2d\u2026');var content=await zip.generateAsync({type:'blob',compression:'DEFLATE'});var d=new Date(),ds=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');saveAs(content,'\u6c7d\u8fd0_'+ds+'.zip');setTimeout(hd,500);st('\u2705','\u5bfc\u51fa\u5b8c\u6210: '+tf.length+'\u4e2a\u6587\u4ef6\u5939, '+total+'\u5f20\u7167\u7247');}catch(e){console.error(e);hd();st('\u274c','\u5bfc\u51fa\u5931\u8d25');}};
    async function init(){try{document.getElementById('today-date').textContent=fd(Date.now());await openDB();await loadFolders();setTimeout(function(){document.getElementById('splash-screen').classList.add('hidden')},600);}catch(e){console.error('init failed:',e);document.getElementById('splash-screen').classList.add('hidden');st('\u274c','\u521d\u59cb\u5316\u5931\u8d25: '+e.message);}}
    document.addEventListener('visibilitychange',function(){if(!document.hidden&&!cfid)loadFolders();});
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();